# -*- coding: utf-8 -*-
"""Seaborn_color_palettes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ThF2mPq8jTc683ALVZFVw4VnP8J_cb3U
"""

# Commented out IPython magic to ensure Python compatibility.
# Importing required Libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Setting a figure size for all the plots we shall be drawing in this kernel:
sns.set(rc={"figure.figsize": (6, 6)})

current_palette = sns.color_palette()
sns.palplot(current_palette)

sns.palplot(sns.color_palette("hls", 8))

sns.palplot(sns.color_palette("husl", 8))

sample_colors = ["windows blue", "amber", "greyish", "faded green", "dusty purple", "pale red", "medium green", "denim blue"]
sns.palplot(sns.xkcd_palette(sample_colors))

# Default Matplotlib Cubehelix version:
sns.palplot(sns.color_palette("cubehelix", 8))

# Default Seaborn Cubehelix version:
sns.palplot(sns.cubehelix_palette(8))

sns.palplot(sns.cubehelix_palette(n_colors=8, start=1.7, rot=0.2, dark=0, light=.95, reverse=True))

# Loading up built-in dataset:
tips = sns.load_dataset("tips")

# Creating Strip plot for day-wise revenue:
sns.stripplot(x="day", y="total_bill", data=tips, color="g")

# Set Theme:
sns.set_style('whitegrid')

# Creating Strip plot for day-wise revenue:
sns.swarmplot(x="day", y="total_bill", data=tips, palette="viridis")

iris = sns.load_dataset("iris")

sns.boxplot(x="species", y="petal_length", data=iris, palette="cividis")
